### ISSUE TITLE
Error in compiling rtpose_wrapper

### ISSUE THREAD

**Issue by Harsharma2308** [OpenPTrack/open_ptrack_v2#44]
I am not able to compile rtpose_wrapper as it  seems to be requiring older caffe version with CUDA 7.5.
Need help on compiling this. If anyone faced issue and solved, do help

**Comment by SimeonOA** [comment]
Hi

Please could you post the exact error that you are getting during your compiling.

Thank you.

Simeon

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Harsharma2308** [comment]
This is the error I am getting.
> /usr/bin/ld: warning: libcudart.so.7.5, needed by /usr/lib/libcaffe.so, not found (try using -rpath or -rpath-link)
> /usr/bin/ld: warning: libcudart.so.7.5, needed by /usr/lib/libcaffe.so, not found (try using -rpath or -rpath-link)
> /usr/bin/ld: warning: libcudart.so.7.5, needed by /usr/lib/libcaffe.so, not found (try using -rpath or -rpath-link)
> /usr/bin/ld: warning: libcudart.so.7.5, needed by /usr/lib/libcaffe.so, not found (try using -rpath or -rpath-link)
> /usr/bin/ld: warning: libcudart.so.7.5, needed by /usr/lib/libcaffe.so, not found (try using -rpath or -rpath-link)
> .build_release/tools/extract_features.o: In function `int feature_extraction_pipeline<float>(int, char**)':
> extract_features.cpp:(.text._Z27feature_extraction_pipelineIfEiiPPc[_Z27feature_extraction_pipelineIfEiiPPc]+0x165): undefined reference to `caffe::Net<float>::Net(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, caffe::Phase, int, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const*, caffe::Net<float> const*)'
> collect2: error: ld returned 1 exit status
> Makefile:621: recipe for target '.build_release/tools/extract_features.bin' failed
> make: *** [.build_release/tools/extract_features.bin] Error 1
> make: *** Waiting for unfinished jobs....
> /usr/bin/ld: warning: libcudart.so.7.5, needed by /usr/lib/libcaffe.so, not found (try using -rpath or -rpath-link)
> /usr/bin/ld: warning: libcudart.so.7.5, needed by /usr/lib/libcaffe.so, not found (try using -rpath or -rpath-link)
> .build_release/tools/caffe.o: In function `test()':
> caffe.cpp:(.text+0x15b7): undefined reference to `caffe::Net<float>::Net(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, caffe::Phase, int, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const*, caffe::Net<float> const*)'
> .build_release/tools/caffe.o: In function `train()':
> caffe.cpp:(.text+0x316e): undefined reference to `caffe::P2PSync<float>::P2PSync(boost::shared_ptr<caffe::Solver<float> >, caffe::P2PSync<float>*, caffe::SolverParameter const&)'
> caffe.cpp:(.text+0x319b): undefined reference to `caffe::P2PSync<float>::Run(std::vector<int, std::allocator<int> > const&)'
> caffe.cpp:(.text+0x31a3): undefined reference to `caffe::P2PSync<float>::~P2PSync()'
> caffe.cpp:(.text+0x461e): undefined reference to `caffe::P2PSync<float>::~P2PSync()'
> .build_release/tools/caffe.o: In function `time()':
> caffe.cpp:(.text+0x4843): undefined reference to `caffe::Net<float>::Net(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, caffe::Phase, int, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const*, caffe::Net<float> const*)'
> caffe.cpp:(.text+0x4bad): undefined reference to `caffe::Layer<float>::Lock()'
> caffe.cpp:(.text+0x4ca2): undefined reference to `caffe::Layer<float>::Unlock()'
> collect2: error: ld returned 1 exit status
> Makefile:621: recipe for target '.build_release/tools/caffe.bin' failed
> make: *** [.build_release/tools/caffe.bin] Error 1
>

**Comment by SimeonOA** [comment]
Hi 

Please refer to this [point]() in the WIKI. 
The correct commands to run are :

```
 cd ~/workspace/ros/src
 git clone https://bitbucket.org/mcarraro/rtpose_wrapper
 cd rtpose_wrapper
 git checkout integration-1604
 sudo apt-get --assume-yes install libprotobuf-dev libleveldb-dev libsnappy-dev libhdf5-serial-dev protobuf-compiler libboost-all-dev libgflags-dev libgoogle-glog-dev liblmdb-dev
 make all -j8
```

Please let us know if this fix your error.

Thanks 
Simeon

**Comment by Harsharma2308** [comment]
I did follow all those commands first. Though I removed and cloned everything again. And it works. Thanks for the quick reply.

**Comment by JimZhou-001** [comment]
Hello, I meet the errors. How can I solve the problem? Thank you!

find: `examples': No such file or directory
find: `examples': No such file or directory
find: `examples': No such file or directory
CXX src/caffe/common.cpp
In file included from ./include/caffe/util/device_alternate.hpp:40:0,
                 from ./include/caffe/common.hpp:19,
                 from src/caffe/common.cpp:7:
./include/caffe/util/cudnn.hpp:5:19: fatal error: cudnn.h: No such file or directory
compilation terminated.
Makefile:577: recipe for target '.build_release/src/caffe/common.o' failed
make: *** [.build_release/src/caffe/common.o] Error 1
